[workspace]
resolver = "2"
members = ["lib", "cli", "editor", "project"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
plottery_lib = "0.1.0"
plottery_project = { path = "project" }
plottery_cli = { path = "cli" }
plottery_project_macros = "0.1.0"
