[package]
name = "plottery"
version = "0.1.0"
authors = ["Tobias Grothmann <tobiasgrothmannplotterart@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
geo = "0.27.0"
geo-types = "0.7.12"
geometry-predicates = "0.3.0"
itertools = "0.12.0"
anyhow = "1.0.75"
cargo-generate = "0.19.0"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.50"
toml = "0.8.8"
tempfile = "3.8.1"

[lib]
name = "plottery_lib"
path = "src/lib.rs"