[package]
name = "plottery_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
plottery_lib = { path = "../lib" }
itertools = "0.12.0"
anyhow = "1.0.75"
cargo-generate = "0.19.0"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.50"
toml = "0.8.8"
tempfile = "3.8.1"
libloading = "0.8.1"
clap = "4.4.11"
resvg = "0.37.0"
path-absolutize = "3.1.1"

[[bin]]
name = "plottery_cli"
path = "src/main.rs"
