[package]
name = "plottery_cli"
version = "0.1.0"
edition = "2021"
description = "Command line interface of Plottery, a creative coding framework for generative vector graphics and pen plotting."
authors = ["Tobias Grothmann <tobiasgrothmannplotterart@gmail.com>"]

[dependencies]
plottery_project = { path = "../project" }
thiserror = "1.0.50"
clap = { version = "4.4.18", features = ["derive"] }
