[package]
name = "plottery_editor"
version = "0.1.0"
edition = "2021"
description = "Plottery Editor to manage Plottery projects."

[package.metadata.bundle]
name = "Plottery Editor"
icon = ["plottery/icon_512.png"]
identifier = "de.tobiasgrothmann.plottery"
version = "0.0.1"
copyright = "Copyright (c) Tobias Grothmann 2023. All rights reserved."
category = "Developer Tool"
short_description = "Editor to manage Plottery projects."
long_description = "Editor to manage Plottery projects."

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
directories = "5.0.1"
plottery_lib = { path = "../lib" }
plottery_project = { path = "../project" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dioxus-logger = { version = "0.4.1", features = ["timestamps"] }
log = "0.4.20"
path-absolutize = "3.1.1"
chrono = "0.4.31"
dioxus-router = "0.4.3"
os_type = "2.6.0"
dioxus-std = { version = "0.4.2", features = ["utils"] }
tokio = "1.35.1"
notify = "6.1.1"
nix = { version = "0.27.1", features = ["signal"] }
opener = { version = "0.6.1", features = ["reveal"] }
rfd = "0.11"
regex = "1.10.3"

[[bin]]
name = "PlotteryEditor"
path = "src/main.rs"
