[application]

# App (Project) Name
name = "{{project-name}}"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

icon = "public/icon512.svg"

[web.app]

# HTML title tag content
title = "{{project-name}}"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
