[package]
name = "plottery_project_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = ">=2.0.59"
quote = "1.0"
plottery_project_params = { path = "../project_params" }
