[workspace]

[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
{{plottery-lib-include}}
{{plottery-project-include}}
serde = { version = "1.0.195", features = ["derive"] }
