[workspace]

[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
open = "5.1.2"
{{plottery-lib-include}}
{{plottery-project-include}}
tempfile = "3.8.0"
